ALTER TABLE employees ADD COMPANY VARCHAR(20) NULL 
CONSTRAINT company_ref DEFAULT 'LG';

ALTER TABLE employees DROP CONSTRAINT company_ref,COLUMN COMPANY;

ALTER TABLE employees ALTER COLUMN PHONE VARCHAR(20)
SELECT * FROM employees