USE sample
GO

BEGIN
	DECLARE @NAME VARCHAR(20),@SALARY DECIMAL(10,2),@DEPTID INTEGER;
	SELECT @NAME=NAME , @SALARY=SALARY FROM LMS
	WHERE DEPTID=10;
	SELECT @NAME AS NAME,@SALARY AS SALARY, @DEPTID AS DEPTID;
	BEGIN
		PRINT 'DEPARTMENT ID: ' +'@DEPTID';
	END
END
GO