SELECT GETDATE()

SELECT CURRENT_TIMESTAMP

SELECT SYSDATETIME()

SELECT DATENAME(MONTH,GETDATE())

SELECT DATENAME(DAY,GETDATE())

SELECT DATENAME(HOUR,GETDATE())

SELECT DATEDIFF(YEAR,'OCTOBER 8 2002',CURRENT_TIMESTAMP)
SELECT DATEDIFF(MONTH,'OCTOBER 5 2021','FEBRUARY 20 2024')

SELECT DATEADD(YEAR,100,SYSDATETIME())