CREATE TRIGGER tr_msg
ON LMS
AFTER 
INSERT
AS 
BEGIN
	PRINT 'Welcome to the Company';
END;

INSERT INTO LMS VALUES(5,'HJK',4562231,40);

CREATE TABLE LMSLogs
( id Integer,Name Varchar(20),salary decimal(10,2),deptid integer,modifiedby varchar(20),modifiedon date);

#INSERT
CREATE TRIGGER after_Insert
ON LMS
AFTER
INSERT
AS
BEGIN
	INSERT INTO LMSLogs
	SELECT EMPID,Name,SALARY,DEPTID,'Garv',GETDATE()
	FROM INSERTED;
END;

SELECT * FROM LMS;
SELECT * FROM LMSLogs;

INSERT INTO LMS VALUES(6,'ADW',787976,70);

#uPDATE
CREATE TRIGGER after_update
ON LMS
AFTER
UPDATE
AS
BEGIN
	INSERT INTO LMSLogs
	SELECT EMPID,Name,SALARY,DEPTID,'Garv',GETDATE()
	FROM INSERTED;
END;

SELECT * FROM LMS;
SELECT * FROM LMSLogs;

UPDATE LMS SET SALARY-=10000 WHERE NAME='ADW';

#DELETE
CREATE TRIGGER after_delete
ON LMS
AFTER
DELETE
AS
BEGIN
	INSERT INTO LMSLogs
	SELECT EMPID,Name,SALARY,DEPTID,'Garv',GETDATE()
	FROM deleted;
END;

SELECT * FROM LMS;
SELECT * FROM LMSLogs;

DELETE FROM LMS WHERE DEPTID=30;

 
CREATE TRIGGER after_INSERT_UPDATE_DELETE
ON LMS
AFTER
INSERT,DELETE,UPDATE
AS
BEGIN
	IF EXISTS(SELECT * FROM inserted) AND NOT EXISTS(SELECT * FROM deleted)
	BEGIN
		INSERT INTO LMSLogs
		SELECT EMPID,Name,SALARY,DEPTID,'ABC',GETDATE()
		FROM deleted;
	END;

	ELSE IF EXISTS(SELECT * FROM inserted) AND EXISTS(SELECT * FROM deleted)
	BEGIN
		INSERT INTO LMSLogs
		SELECT EMPID,Name,SALARY,DEPTID,'ABC',GETDATE()
		FROM deleted;
	END;

	ELSE IF EXISTS(SELECT * FROM deleted) AND NOT EXISTS(SELECT * FROM inserted)
	BEGIN		
		INSERT INTO LMSLogs
		SELECT EMPID,Name,SALARY,DEPTID,'ABC',GETDATE()
		FROM deleted;
	END;

	ELSE
	BEGIN
		PRINT 'NOTHING CHANGES';
	END;
END;

SELECT * FROM LMS;
SELECT * FROM LMSLogs;

INSERT INTO LMS VALUES(7,'NDG',462127,80);
UPDATE LMS SET SALARY-=10000 WHERE NAME='NJD';
DELETE FROM LMS WHERE DEPTID=20;