BEGIN
	DECLARE @SALARY DECIMAL;
	SELECT @SALARY=MIN(SALARY) FROM LMS;
	IF @SALARY < 8000
		BEGIN
			PRINT 'MIN SALARY LESS THAN 8000';
		END
END
GO

BEGIN
	DECLARE @SALARY DECIMAL;
	SELECT @SALARY=AVG(SALARY) FROM LMS;
	IF @SALARY > 8000
		BEGIN
			PRINT 'AVG SALARY GREATER THAN 8000';
		END
	ELSE
		BEGIN
			PRINT 'AVG SALARY LESS THAN 8000';
		END
END
GO