CREATE FUNCTION multiLine(@id INTEGER)
RETURNS @table_variable TABLE
(ID  INT,NAME VARCHAR(10),SALARY DECIMAL,DEPTID INT)
AS
BEGIN
	INSERT INTO @table_variable 
	SELECT * FROM LMS WHERE DEPTID=@id;
	RETURN
END;
GO

SELECT * FROM multiLine(10);