CREATE DATABASE UserEngagementMIS;
USE UserEngagementMIS;

CREATE TABLE LMS
(
EMPID INTEGER PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
SALARY DECIMAL(10,2),
DEPTID INTEGER
);
INSERT INTO LMS VALUES(04,'NJD',51000,60);

CREATE TABLE MACHINELOGS
(DeptId Integer Primary Key,
Experience Integer
);
INSERT INTO MACHINELOGS VALUES(40,5);

SELECT * FROM LMS
SELECT * FROM MACHINELOGS

SELECT *
FROM LMS AS L
INNER JOIN MACHINELOGS AS M
ON L.DEPTID=M.DeptId;

SELECT *
FROM LMS AS L
LEFT JOIN MACHINELOGS AS M
ON L.DEPTID=M.DeptId;

SELECT *
FROM LMS AS L
RIGHT JOIN MACHINELOGS AS M
ON L.DEPTID=M.DeptId;

SELECT *
FROM LMS AS L
FULL JOIN MACHINELOGS AS M
ON L.DEPTID=M.DeptId;

SELECT *
FROM LMS AS L
CROSS JOIN MACHINELOGS AS M
