SELECT ABS(SALARY)
FROM employees
WHERE Name='Garv';

SELECT CEILING(SALARY)
FROM employees
WHERE Name='Garv';

SELECT FLOOR(SALARY)
FROM employees
WHERE Name='Garv';

SELECT SQUARE(SALARY)
FROM employees
WHERE Name='Garv';

SELECT SQRT(SALARY)
FROM employees
WHERE Name='Garv';