USE [sample]
GO
/****** Object:  Table [dbo].[LMS]    Script Date: 2/22/2024 3:12:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LMS](
	[EMPID] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[SALARY] [decimal](10, 2) NULL,
	[DEPTID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MACHINELOGS]    Script Date: 2/22/2024 3:12:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MACHINELOGS](
	[DeptId] [int] NOT NULL,
	[Experience] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DeptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOURCE]    Script Date: 2/22/2024 3:12:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOURCE](
	[NAME] [varchar](10) NULL,
	[QUANTITY] [int] NULL,
	[PRICE] [decimal](18, 0) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TARGET]    Script Date: 2/22/2024 3:12:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TARGET](
	[NAME] [varchar](10) NULL,
	[QUANTITY] [int] NULL,
	[PRICE] [decimal](18, 0) NULL
) ON [PRIMARY]
GO
INSERT [dbo].[LMS] ([EMPID], [Name], [SALARY], [DEPTID]) VALUES (1, N'Garv', CAST(10000.00 AS Decimal(10, 2)), 10)
INSERT [dbo].[LMS] ([EMPID], [Name], [SALARY], [DEPTID]) VALUES (2, N'ABC', CAST(5000.00 AS Decimal(10, 2)), 30)
INSERT [dbo].[LMS] ([EMPID], [Name], [SALARY], [DEPTID]) VALUES (3, N'Abd', CAST(523560.00 AS Decimal(10, 2)), 20)
INSERT [dbo].[LMS] ([EMPID], [Name], [SALARY], [DEPTID]) VALUES (4, N'NJD', CAST(51000.00 AS Decimal(10, 2)), 60)
GO
INSERT [dbo].[MACHINELOGS] ([DeptId], [Experience]) VALUES (10, 5)
INSERT [dbo].[MACHINELOGS] ([DeptId], [Experience]) VALUES (20, 9)
INSERT [dbo].[MACHINELOGS] ([DeptId], [Experience]) VALUES (30, 20)
INSERT [dbo].[MACHINELOGS] ([DeptId], [Experience]) VALUES (40, 5)
GO
INSERT [dbo].[SOURCE] ([NAME], [QUANTITY], [PRICE]) VALUES (N'A', 10, CAST(15 AS Decimal(18, 0)))
INSERT [dbo].[SOURCE] ([NAME], [QUANTITY], [PRICE]) VALUES (N'B', 15, CAST(50 AS Decimal(18, 0)))
INSERT [dbo].[SOURCE] ([NAME], [QUANTITY], [PRICE]) VALUES (N'C', 20, CAST(25 AS Decimal(18, 0)))
GO
INSERT [dbo].[TARGET] ([NAME], [QUANTITY], [PRICE]) VALUES (N'A', 16, CAST(20 AS Decimal(18, 0)))
INSERT [dbo].[TARGET] ([NAME], [QUANTITY], [PRICE]) VALUES (N'B', 16, CAST(20 AS Decimal(18, 0)))
INSERT [dbo].[TARGET] ([NAME], [QUANTITY], [PRICE]) VALUES (N'C', 16, CAST(20 AS Decimal(18, 0)))
GO
USE [master]
GO
ALTER DATABASE [UserEngagementMIS] SET  READ_WRITE 
GO
